### PR TITLE
remove default button priority and size

### PR DESCRIPTION
**Pull request by jonathanadler**
### 👀  PR is ready for review 

- [x] Ready for review

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_535/

**Review by sivanharel — COMMENTED** [review]
I understand the issue and that we don't want to use long selectors in order to override the default design of the button component in the dropdowns but it makes the Button.st.css file unreadable and hard to maintain :(
Maybe we should find another way? Maybe we could talk with Tom Raviv or Barak.

**Comment by jonathanadler** [comment]
> I understand the issue and that we don't want to use long selectors in order to override the default design of the button component in the dropdowns but it makes the Button.st.css file unreadable and hard to maintain :(
> Maybe we should find another way? Maybe we could talk with Tom Raviv or Barak.

🤔 
I didn't feel this change caused the file to be unreadable. 
I actually felt the opposite, since I'm removing the use of stylable.
I converted stylable to regular css in this PR

**Comment by sivanharel** [comment]
> > I understand the issue and that we don't want to use long selectors in order to override the default design of the button component in the dropdowns but it makes the Button.st.css file unreadable and hard to maintain :(
> > Maybe we should find another way? Maybe we could talk with Tom Raviv or Barak.
> 
> 🤔
> I didn't feel this change caused the file to be unreadable.
> I actually felt the opposite, since I'm removing the use of stylable.
> I converted stylable to regular css in this PR

Yeah, you are right it's a trade of which component st.css file would be more readable. I mean now the dropdown is more readable but the button is a bit less readable.
I feel that it is not so intuitive for someone from outside why does the css is also added directly on the root without the size and priority states.
But ok maybe it is not so critical.

**Comment by jonathanadler** [comment]
> > > I understand the issue and that we don't want to use long selectors in order to override the default design of the button component in the dropdowns but it makes the Button.st.css file unreadable and hard to maintain :(
> > > Maybe we should find another way? Maybe we could talk with Tom Raviv or Barak.
> > 
> > 
> > 🤔
> > I didn't feel this change caused the file to be unreadable.
> > I actually felt the opposite, since I'm removing the use of stylable.
> > I converted stylable to regular css in this PR
> 
> Yeah, you are right it's a trade of which component st.css file would be more readable. I mean now the dropdown is more readable but the button is a bit less readable.
> I feel that it is not so intuitive for someone from outside why does the css is also added directly on the root without the size and priority states.
> But ok maybe it is not so critical.
> I just feel that we are doing some workarounds because we don't have a better solution from stylable.

But also in the Button component, assigning the styles for the root itself is just regular css.
Isn't it clear that it's the default styling of the component?

**Review by sivanharel — APPROVED** [review]

**Pull request merged**
