### PR TITLE
fix contribution md ref

### PR DESCRIPTION
**Pull request by wildcard**
# ✨ Pull Request

### 💁 Description

Fixed WixDoc contribution md file ref - it was a broken link

### 💭 Motivation

I want dev to contribute & discover the project via WixDocs

### 👀  PR is ready for review 

- [X] Ready for review

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_580/

**Review by jonathanadler — APPROVED** [review]

**Comment by wildcard** [comment]
#automerge

**Comment by wildcard** [comment]
Ouch the tests are failing for some reason

**Comment by jonathanadler** [comment]
> Ouch the tests are failing for some reason

Lot's of flakiness today :(

**Comment by jonathanadler** [comment]
You'll have to pull-rebase for the tests to pass

**Comment by wildcard** [comment]
Thanks! Sorry for the n00b reply 🙈 but say why the tests are not running on a rebased branch of the PR? (If I'm not wrong that's an industry standard 🤓)

**Comment by jonathanadler** [comment]
> Thanks! Sorry for the n00b reply 🙈 but say why the tests are not running on a rebased branch of the PR? (If I'm not wrong that's an industry standard 🤓)

I believe it used to be that way, until about a year ago.
I'm not sure why it was changed 🤷‍♂️

**Pull request merged**
