### PR TITLE
build(Perfer) - add codemod for generator

### PR DESCRIPTION
**Pull request by nitayneeman**
This PR adds a codemod that allows initializing a default threshold when creating a new component using the generator.

It looks like this:
image

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_525/

**Review by sivanharel — APPROVED** [review]
Nice:)

**Comment by jonathanadler** [comment]
Nice!

Do we have a way to update the threshold once the new component development is finished?

**Comment by nitayneeman** [comment]
> Nice!
> 
> Do we have a way to update the threshold once the new component development is finished?

We just need to go to:
https://github.com/wix/wix-ui-tpa/blob/master/perfer.config.js#L2

And update the number.

In order to know if we can change it, we should run `npm run test:perfer-bundles` and see the actual bundle size. Also we can make a PR and see the actual size on Perfer's CI report.

**Pull request merged**
