### PR TITLE
counter  increase buttons click area

### PR DESCRIPTION
**Pull request by mariakwix**
Counter buttons clickable are is currently very small. can we fix this like so?

### CODE REVIEW

**Comment by jonathanadler** [comment]
hey @mariakwix 👋 

Please sign your commits in order for the build to run 🙏 

https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits

Thanks!

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_520/

**Review by sivanharel — COMMENTED** [review]
Hi @mariakwix,
First of all, thank you for contributing to the library.

There is an issue with your solution, when it's a big number it overlaps the text so the flex-shrink: 1 couldn't be on the button and the icons are now closer to the text

I talked with our designer to ask her about an alternative solution and she said that the current size of the button which is 24px *24px is bigger than the icon itself and should be enough.
If there is a specific issue with that and users complain about it, you could ask your designer to talk to our designer (@michalvardi )

**Comment by jonathanadler** [comment]
Closing this for now

**Pull request closed without merging**
