### PR TITLE
feat(Counter): Add `stopPropagation` prop

### PR DESCRIPTION
**Pull request by GuyPerkal**

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_433/

**Comment by jonathanadler** [comment]
@GuyPerkal 
Seems a bit intrusive
Can you explain why this is needed?

**Comment by GuyPerkal** [comment]
We have a clickable container that has counters in it, and we'd like to prevent counters from trigger the container's click event. It's not a must to add this prop since it's possible to wrap the counter with an element that stops propagation, but I figured it's nice to have and would be less hacky.

**Comment by GuyPerkal** [comment]
Sure, you can see it here - https://gilada.wixsite.com/sunny-falafel/mainpage

Add an item to the cart and then open the cart, the item in the cart is clickable and has a counter in it. Currently the propagation is stopped by wrapping with a div, otherwise clicking the counter would open the dish modal.

**Comment by jonathanadler** [comment]
> Sure, you can see it here - https://gilada.wixsite.com/sunny-falafel/mainpage
> 
> Add an item to the cart and then open the cart, the item in the cart is clickable and has a counter in it. Currently the propagation is stopped by wrapping with a div, otherwise clicking the counter would open the dish modal.

I understand...

Usually, we don't expect to have an interactive element like this, inside of a clickable container.
I'm not sure this is something we would want to maintain in the library.

**Comment by GuyPerkal** [comment]
No problem, closing this PR.

**Pull request closed without merging**
