### PR TITLE
fix(infra) - update the success and error colors to accessible colors

### PR DESCRIPTION
**Pull request by sivanharel**

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_442/

**Review by jonathanadler — APPROVED** [review]
And these are all the places that we use these colors?

**Comment by sivanharel** [comment]
> And these are all the places that we use these colors?

I am checking with Michal if we should change the LikeButton checked color as well or not.
Beside that everything was changed.

**Comment by jonathanadler** [comment]
> > And these are all the places that we use these colors?
> 
> I am checking with Michal if we should change the LikeButton checked color as well or not.
> Beside that everything was changed.

Excellent

**Comment by sivanharel** [comment]
> > > And these are all the places that we use these colors?
> > 
> > 
> > I am checking with Michal if we should change the LikeButton checked color as well or not.
> > Beside that everything was changed.
> 
> Excellent

Ok, she said to keep it as is. So I will merge the PR :)

**Pull request merged**
