### PR TITLE
Image - implement hover effects

### PR DESCRIPTION
**Pull request by nitayneeman**
# ✨ Pull Request

### 💁 Description

This PR adds a new prop called `hoverEffect` supporting two vales (`zoom` & `darken`) according to the spec.

### 👀  PR is ready for review 

- [X] Ready for review

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_651/

**Comment by nitayneeman** [comment]
It seems like the hover doesn't work well in the visuals - I'm trying to understand why

**Review by jonathanadler — APPROVED** [review]
Looks great!

Do we want to pass the prop to the Thumbnail image as well?

**Comment by nitayneeman** [comment]
> Looks great!
> 
> Do we want to pass the prop to the Thumbnail image as well?

Currently both Hero & Thumbnail derive all props from Image, so it's supported and passed automatically. For Thumbnail I think we do want it, but for Hero I'm not really sure - I asked @michalvardi.

**Pull request merged**
