### PR TITLE
extend jasmine timeouts

### PR DESCRIPTION
**Pull request by jonathanadler**
Hoping this will help us with flaky tests

### 👀  PR is ready for review 

- [x] Ready for review

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_621/

**Review by nitayneeman — APPROVED** [review]

**Comment by shlomitc** [comment]
It wont :)

**Comment by jonathanadler** [comment]
> It wont :)

😞 
@shlomitc I'm guessing you've already tried this in WSR?

**Comment by shlomitc** [comment]
Yes, the timeout is just mentioning the interaction with applitools failed for some reason. either because it's a network failure, connection issue, or others.
We just reduced as many e2es as we can and moved to visual

**Comment by jonathanadler** [comment]
> Yes, the timeout is just mentioning the interaction with applitools failed for some reason. either because it's a network failure, connection issue, or others.
> We just reduced as many e2es as we can and moved to visual

😭

**Pull request closed without merging**
