### PR TITLE
<Tabs/> a11y: Add aria-label and aria-labelledby;

### PR DESCRIPTION
**Pull request by kranux**

### CODE REVIEW

**Comment by jonathanadler** [comment]
Oh @kranux , forgot to mention that your commits should be signed in order for the builds to run.
You can follow the guide here:
https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_481/

**Review by jonathanadler — APPROVED** [review]
Awesome!
Thanks for the PR.

I'm approving, but I still want to wait for Alon's response before I merge.

**Comment by kranux** [comment]
Thanks! Let's wait :)

**Comment by kranux** [comment]
@jonathanadler I have a confirmation from Alon that it should go on `nav` :)

**Comment by kranux** [comment]
And also, I'm not authorized to merge it :)

image

**Pull request merged**
