### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by jonathanadler**

### CODE REVIEW

**Comment by jonathanadler** [comment]
@NitzanSirota @argshook 
I manually squashed and merged your PR to this branch.
We'll continue to use this branch for all the changes for the Major release.

**Comment by NitzanSirota** [comment]
> @NitzanSirota @argshook
> I manually squashed and merged your PR to this branch.
> We'll continue to use this branch for all the changes for the Major release.

👍

**Comment by jonathanadler** [comment]
btw @NitzanSirota 
If you're interested in understanding why our PR's (with v2 as base) visual tests failed, then you can see the ticket i've opened to CI: https://jira.wixpress.com/browse/CI-16803

**Comment by argshook** [comment]
@jonathanadler hey, maybe you can update on status of this PR? is there anything blocking from merging it?

i thought this was already done, but missed it

**Comment by jonathanadler** [comment]
> @jonathanadler hey, maybe you can update on status of this PR? is there anything blocking from merging it?
> 
> i thought this was already done, but missed it

@argshook 
I wanted to merge other breaking PR's into this one, but didn't get a chance to do that yet.
Also, since I'm on a low wix-ui-tpa capacity at the moment, I wasn't sure it would be a good idea to merge now, since I won't have much time to give support to our consumers

**Pull request merged**
