### PR TITLE
Test applitools batch

### PR DESCRIPTION
**Pull request by jonathanadler**

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_497/

**Comment by jonathanadler** [comment]
@shlomitc 
So I guess something changed in CI:https://pullrequest-tc.dev.wixpress.com/viewLog.html?tab=buildLog&buildTypeId=FedInfra_WixUiTpa&buildId=13368111&_focus=677

```bash
[21:33:57]	[npm run test] BATCH ID:
[21:33:57]	[npm run test] =========
[21:33:57]	[npm run test] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[21:33:57]	[npm run test] @@@@@@@@@@@@@@@@@@ headCommitHash @@@@@@@@@@@@@@@@@@@@@
[21:33:57]	[npm run test] ebb4c7fb871208a0bb54eddf379ed21d7118ba11
[21:33:57]	[npm run test] 
[21:33:57]	[npm run test] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[21:33:57]	[npm run test] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[21:33:57]	[npm run test] @@@@@@@@@@@@@@@@@@ parentsHashArr @@@@@@@@@@@@@@@@@@@@@
[21:33:57]	[npm run test] ebb4c7fb871208a0bb54eddf379ed21d7118ba11 cf0f608862910033cff8ce39f0cdba11651306c3
[21:33:57]	[npm run test] 
[21:33:57]	[npm run test] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[21:33:57]	[npm run test] ebb4c7fb871208a0bb54eddf379ed21d7118ba11
```

`parentsHashArr` should have 3 hashes

**Comment by shlomitc** [comment]
I wonder if we can ask the CI team to adopt this thing: https://github.com/applitools/eyes.teamcity
It knows how to export calculate the batch id and expose it as a standard teamcity variable.

**Comment by jonathanadler** [comment]
> I wonder if we can ask the CI team to adopt this thing: https://github.com/applitools/eyes.teamcity
> It knows how to export calculate the batch id and expose it as a standard teamcity variable.

Very interesting!

**Comment by jonathanadler** [comment]
@shlomitc 
Seem to be back to normal

**Pull request closed without merging**
