### PR TITLE
Radio button group

### PR DESCRIPTION
**Pull request by mariakwix**

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_402/

**Comment by jonathanadler** [comment]
Hey @mariakwix 
can you give some background for this PR?

**Comment by shlomitc** [comment]
This looks stale for a while now. can we close it?

**Comment by jonathanadler** [comment]
Closing for now.

**Pull request closed without merging**
