### PR TITLE
[wix-ui-tpa] TextArea: fix accessibility- border all frame

### PR DESCRIPTION
**Pull request by shlaskt**
Issue: https://github.com/wix/wix-ui-tpa/issues/496
Fix- move padding to textarea

### CODE REVIEW

**Comment by jonathanadler** [comment]
It looks great, just one small thing.
In order for the build and tests to run, you'll need to create a signed commit.
You can read about how to do it here: https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md
and then just make some dummy commit, push, and it will run.

Thanks for the contribution!

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_506/

**Comment by jonathanadler** [comment]
@shlaskt 
First of all, thanks again!

Second, as you probably noticed, the visual tests are failing, since this is a breaking change.

I'll check with our designers if this change is ok, 
If not, we might need to manually set the focus-ring, which means manually maintain a `focus`-ed state

**Comment by shlaskt** [comment]
@jonathanadler yes I see that it's needed the bottom padding with the current design, and now the text cuts at the last line for long text. Unfortunately, I didnt find any solution to handle it with the focus ring.
The second option sounds good also.

**Pull request closed without merging**
