### PR TITLE
fix #601

### LINKED ISSUE #601: Usage of un-scoped element
https://github.com/wix/wix-ui-tpa/blob/5c54771c1fc5fb81b6a76b93cbf75ad0277324fe/src/components/Button/Button.st.css#L286

There is a `mobile` element in few selectors here but I think it should be `:mobile`

Do you have any build warnings?

### PR DESCRIPTION
**Pull request by jonathanadler**
Fixes #601 

### 👀  PR is ready for review 

- [x] Ready for review

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_603/

**Review by nitayneeman — APPROVED** [review]
BTW we said that we're going to get rid of the st states at some point, right? 😵

**Comment by jonathanadler** [comment]
> BTW we said that we're going to get rid of the st states at some point, right? 😵

Well, I don't know if we get rid of them, but It's better to not add new ones.
In any case, the `mobile` state is a bit different, since it's an applicative state, and not a variation of the component

**Comment by ronami** [comment]
Hey, any chance this can be merged? 🙏

**Comment by jonathanadler** [comment]
> Hey, any chance this can be merged? 🙏

@ronami 
I'll try to make the build pass.
Just out of curiosity, how does this affect you 😄 ?

**Comment by jonathanadler** [comment]
> > Hey, any chance this can be merged? 🙏
> 
> @ronami
> I'll try to make the build pass.
> Just out of curiosity, how does this affect you 😄 ?

@ronami 
this change breaks our visual tests, cause it has a bad affect on one of the button's variations.
Can you expand on why this is needed so that we can prioritize?

**Comment by ronami** [comment]
Oh sorry, took me a bit of time to see the mention. I'm working on bumping Yoshi's webpack version to v5. This component from `wix-ui-tpa` is being used in a lot of projects and creates noise from Stylable v4 whenever developers run `yoshi start` and `yoshi build`.

**Pull request merged**
