### PR TITLE
added text typography - running text 2

### PR DESCRIPTION
**Pull request by poseneror**
Hey, please review and merge, shouldn't be any different than other typos

### CODE REVIEW

**Comment by poseneror** [comment]
Heading M is Paragraph 2, if you think something else should be used I could manage that :)
We have a different task for mobile styles, so it will probably be defined in a later stage.

**Comment by johannaasseraf** [comment]
Lets connect the style of Heading M to H2 of the text themes. The default design should override the text size though

**Comment by poseneror** [comment]
sorry, I meant that body M is connected to Paragraph 2.
Heading-M is Heading-5 from settings

**Comment by johannaasseraf** [comment]
Can we connect it to H2 (just not get the h2 tag for a11y)

**Comment by poseneror** [comment]
Yeah, I think it should be set to 'Page-title'

**Comment by johannaasseraf** [comment]
Page title isn't H1 in the template text themes?
image

**Comment by poseneror** [comment]
There's another preset 'title' which is the H1 preset

**Pull request merged**
