### PR TITLE
(Grid) amount of items do not affect the max items per row

### PR DESCRIPTION
**Pull request by liorMar**
https://zeroheight.com/7sjjzhgo2/p/42435d/b/185be1

### CODE REVIEW

**Comment by jonathanadler** [comment]
@liorMar 
Is there a way to see this in action?
I tried using the [playground](https://wix-wix-ui-tpa-pr-95.surge.sh/?activeTab=Playground&path=%2Fstory%2Fbookings--grid), but it's not so intuitive.

**Comment by johannaasseraf** [comment]
Hey :) I also see some strange things happening in the playground now..
maybe we can hop a call later today?


On 10 June 2019 at 11:36:48, Jonathan Adler (notifications@github.com)
wrote:

@liorMar <https://github.com/liorMar>
Is there a way to see this in action?
I tried using the playground
<https://wix-wix-ui-tpa-pr-95.surge.sh/?activeTab=Playground&path=%2Fstory%2Fbookings--grid>,
but it's not so intuitive.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wix/wix-ui-tpa/pull/95?email_source=notifications&email_token=AI3UXWEGH4RFX5AOAFYPGMDPZYHBZA5CNFSM4HVBH572YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXJIYYI#issuecomment-500337761>,
or mute the thread

**Comment by liorMar** [comment]
> @liorMar
> Is there a way to see this in action?
> I tried using the [playground](https://wix-wix-ui-tpa-pr-95.surge.sh/?activeTab=Playground&path=%2Fstory%2Fbookings--grid), but it's not so intuitive.

@jonathanadler you can increase the `maxColumns` and inspect the `ul`

**Comment by jonathanadler** [comment]
> > @liorMar
> > Is there a way to see this in action?
> > I tried using the [playground](https://wix-wix-ui-tpa-pr-95.surge.sh/?activeTab=Playground&path=%2Fstory%2Fbookings--grid), but it's not so intuitive.
> 
> @jonathanadler you can increase the `maxColumns` and inspect the `ul`

Yeah, so that's what I meant by not intuitive.
I think users should see somehow how this behaves.
I thought about adding an example, but I'd rather have it possible to just see the behaviour when playing with the playground.
Currently the playground doesn't work that good.

**Comment by liorMar** [comment]
> > > @liorMar
> > > Is there a way to see this in action?
> > > I tried using the [playground](https://wix-wix-ui-tpa-pr-95.surge.sh/?activeTab=Playground&path=%2Fstory%2Fbookings--grid), but it's not so intuitive.
> > 
> > 
> > @jonathanadler you can increase the `maxColumns` and inspect the `ul`
> 
> Yeah, so that's what I meant by not intuitive.
> I think users should see somehow how this behaves.
> I thought about adding an example, but I'd rather have it possible to just see the behaviour when playing with the playground.
> Currently the playground doesn't work that good.

i can add an example of 1 item in `maxColumns` of `2` that way the only item will not be centered

**Comment by jonathanadler** [comment]
> > > > @liorMar
> > > > Is there a way to see this in action?
> > > > I tried using the [playground](https://wix-wix-ui-tpa-pr-95.surge.sh/?activeTab=Playground&path=%2Fstory%2Fbookings--grid), but it's not so intuitive.
> > > 
> > > 
> > > @jonathanadler you can increase the `maxColumns` and inspect the `ul`
> > 
> > 
> > Yeah, so that's what I meant by not intuitive.
> > I think users should see somehow how this behaves.
> > I thought about adding an example, but I'd rather have it possible to just see the behaviour when playing with the playground.
> > Currently the playground doesn't work that good.
> 
> i can add an example of 1 item in `maxColumns` of `2` that way the only item will not be centered

Is there a way to have it visible in the playground?

**Comment by liorMar** [comment]
> Is there a way to have it visible in the playground?

@jonathanadler  only if i'll add a fourth option for `items` with `1` item

**Comment by jonathanadler** [comment]
@liorMar 
Let's change the `few` example from 3 to 2

**Comment by liorMar** [comment]
> @liorMar
> Let's change the `few` example from 3 to 2

changed

**Comment by jonathanadler** [comment]
> > @liorMar
> > Let's change the `few` example from 3 to 2
> 
> changed

Did you push? I can't see the change

**Pull request closed without merging**
