### PR TITLE
feat(Dropdown): Add 2 CoreDropdown props to Dropdown

### PR DESCRIPTION
**Pull request by GuyPerkal**
Add flip, fixed and moveBy props, in order to pass them to CoreDropdown.

### CODE REVIEW

**Comment by jonathanadler** [comment]
Thanks @GuyPerkal 
Can you send the use-case for this?
What's the spec you're working with.

If you need it to fix a bug, maybe that's something we'll need to fix it in the component, so everyone could enjoy it.
If it's a design issue, I guess I'll need to get a review from our designers

**Comment by GuyPerkal** [comment]
moveBy isn't actually needed for us right now so I can remove it, but flip and fixed will solve an issue when openning a dropdown in a modal  -

image (2)

image (3)

The dropdown covers the input when opened.

**Comment by jonathanadler** [comment]
@GuyPerkal 
and isn't `placement` enough for this?
```jsx
placement={'bottom'}
```

**Comment by GuyPerkal** [comment]
The screenshot is with placement bottom, that's the default.

**Comment by jonathanadler** [comment]
> The screenshot is with placement bottom, that's the default.

I see

So i'd rather we move the `moveBy` prop, and then we can merge

**Comment by GuyPerkal** [comment]
Done.

**Review by jonathanadler — APPROVED** [review]

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-tpa.pr_392/

**Pull request merged**
